### ISSUE TITLE
R section needs to be expanded

### ISSUE THREAD

**Issue by nselem** [carpentries-lab/metagenomics-analysis#11]
R section needs more analysis, may be include further examples from Phyloseq

**Comment by Bedxxe** [comment]
More analyses and an expanded section regarding diversity, taxonomic assignation, and trimming of the taxonomic database will be added. Also, an expansion on the number of the obtained plots will be carried out

**Comment by Bedxxe** [comment]
Now, we will change episode 8 for an introduction to R

**Comment by Bedxxe** [comment]
We added an introductory lesson to R(Episode 9) and developed all the next two episodes inputting special attention to give a detailed explanation, examples, and contextualization to R important aspects
