### ISSUE TITLE
Add a Metagenomics Workshop Overview

### ISSUE THREAD

**Issue by AbrahamAvelar** [carpentries-lab/metagenomics-analysis#16]
As it is for other Data Carpentry lessons, a workshop overview to include:
- Project Organization and Management for Metagenomics: Data Tidiness
- Introduction to the Command Line: Introducing the Shell
- Data Wrangling and Processing: Background and Metadata
The Workshop Overview also provides a standardized way of sharing the setup.

Examples:
https://datacarpentry.org/ecology-workshop/
https://datacarpentry.org/genomics-workshop/

**Comment by nselem** [comment]
This page has been created https://nselem.github.io/metagenomics-workshop/
