### ISSUE TITLE
Introduce biom format

### ISSUE THREAD

**Issue by nselem** [carpentries-lab/metagenomics-analysis#19]
Kraken-biom is used in the R section, so we need to introduce [biom format](https://biom-format.org/)

**Comment by nselem** [comment]
Kraken-biom is used in the R section, so we need to introduce the [biom format](https://biom-format.org/) from

**Comment by Czirion** [comment]
Briefly describe what is a BIOM file in this episode https://carpentries-incubator.github.io/metagenomics/07-Diversity-tackled-with-R/index.html
