### ISSUE TITLE
Add confidentiality in Data Tidiness

### ISSUE THREAD

**Issue by Czirion** [carpentries-lab/metagenomics-analysis#38]
**Reviewer's comment**: In the [Data Tidiness](https://carpentries-incubator.github.io/organization-metagenomics/01-tidiness/index.html) section could be worth briefly mentioning confidentiality issues that may arise from storing and sharing the metadata, i.e. in the case of human samples or patents.

**To do**: Add a paragraph or box about confidentiality in the Data Tidiness episode.

**Comment by nselem** [comment]
We added the discussion box "Ethical considerations in microbiome studies," where we addressed confidentiality, prior informed consent, policies about result communications, and in general, how to apply the ethical principles: do good, don't harm, respect, and act justly to microbiome studies.
We consulted the following references:  [Mc Guire et al 2008 Ethical, legal, and social considerations in conducting the Human Microbiome Project](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4024738/) and Lange et al. 2022 [Microbiome ethics, guiding principles for microbiome research, use and knowledge management](https://environmentalmicrobiome.biomedcentral.com/articles/10.1186/s40793-022-00444-y)
