### ISSUE TITLE
Create a pipeline with all commands

### ISSUE THREAD

**Issue by nselem** [carpentries-lab/metagenomics-analysis#4]
I think we must have an automatized step

**Comment by Czirion** [comment]
@nselem Do you think this is still needed? If it is, could you elaborate on your idea?

**Comment by nselem** [comment]
I upload a script that comprises all steps in [Diversity Tackled With R](https://github.com/carpentries-incubator/metagenomics-workshop/blob/gh-pages/files/diversity_tackled_with_R.R) and [Taxonomic Analysis with R](https://github.com/carpentries-incubator/metagenomics-workshop/blob/gh-pages/files/taxonomic_analysis_with_R.R)

**Comment by Czirion** [comment]
The code in those episodes will change after I finish the corrections.

**Comment by nselem** [comment]
Sure, once you finished I will update the scripts.
