### ISSUE TITLE
Update zenodo link in Examining Data on the NCBI SRA Database

### ISSUE THREAD

**Issue by Czirion** [carpentries-lab/metagenomics-analysis#41]
**Reviewer's comment**: In the [Examining Data on the NCBI SRA Database](https://carpentries-incubator.github.io/organization-metagenomics/03-ncbi-sra/index.html), the previous version of the zenodo dataset is linked ( [sequencing dataset (from Okie, et al. 2020) adapted for this workshop](https://zenodo.org/record/4285901#.YFtEAq9KjIU)), compared to the dataset linked int the Setup page.

**To do**: Put the permanent DOI

**Comment by nselem** [comment]
Link has been updated
