### ISSUE TITLE
Improve Introducing the Shell

### ISSUE THREAD

**Issue by Czirion** [carpentries-lab/metagenomics-analysis#45]
**Reviewer's comments**:
1) In the [Introducing the Shell](https://carpentries-incubator.github.io/shell-metagenomics/01-introduction/index.html) episode, a consideration could be made for accessing the shell when having a local installation (i.e. not through ssh).
2) A short disclaimer could be added about the differences in output between an AWS instance and a local instance (in order to avoid confusion).
3) In the [Introducing the Shell](https://carpentries-incubator.github.io/shell-metagenomics/01-introduction/index.html) episode, the "Shortcut: Tab Completion" section assumes a different starting point from where the learners might be by that time.

**Comment by nselem** [comment]
@aaronejaime ¿Can you try this issue for Friday? Just add the link to git bash (now git for windows) add the disclaimer, and check in the previous lesson the directory where the user should be located.
