### ISSUE TITLE
Improve Redirection

### ISSUE THREAD

**Issue by Czirion** [carpentries-lab/metagenomics-analysis#47]
**Reviewer's comments**:
1) In the [Redirection](https://carpentries-incubator.github.io/shell-metagenomics/04-redirection/index.html) episode, in the "Exercise 1: Using grep" some additional context on the produced output might be useful (esp. in the 2nd example where it has a long screen).
2) In the [Redirection](https://carpentries-incubator.github.io/shell-metagenomics/04-redirection/index.html) episode, the "File extensions - part 2" part might be a bit confusing, given that the episode flow up until that point, would not lead to the expected error (unless you run the same command twice). It could be useful to clarify this (or slightly rephrase).
3) In the [Redirection](https://carpentries-incubator.github.io/shell-metagenomics/04-redirection/index.html) episode, the "Writing for loops" and "Using Basename in for loops" sections do not have an evaluation associated with it (e.g. an expected output file, or a discussion on how it can be further adapted). Unless this section is critical for other parts of the overall workshop, it may be useful to change it as an "optional" content, keeping only the basename command as part of the content.

**Comment by Czirion** [comment]
3. Added output to for loop and basename commands.

**Comment by AbrahamAvelar** [comment]
1. Added explanation of the answers and expected outputs for Exercise 1

**Comment by AbrahamAvelar** [comment]
2. The boxes 'File extensions'  and 'File extensions - 2' were better set for instructor notes. As part of the lesson, they contained new concepts that did not add to the objectives of this particular lesson.  Therefore, I removed both boxes and suggested these explanations as part of the instructor notes section.
