### ISSUE TITLE
Improve Writing Scripts and Working with Data

### ISSUE THREAD

**Issue by Czirion** [carpentries-lab/metagenomics-analysis#48]
**Reviewr's comments**: 
1) In the [Writing Scripts and Working with Data](https://carpentries-incubator.github.io/shell-metagenomics/05-writing-scripts/index.html) episode, there is no proposed text to write in nano. Although it's understood that this allows for more creativity from the learners, it may be useful to add an example for guidance. Such an example will also assist in the flow of the section on "Writing files", as it is currently a bit unclear.

2) In the [Writing Scripts and Working with Data](https://carpentries-incubator.github.io/shell-metagenomics/05-writing-scripts/index.html) episode, the sentence "You will learn more about writing scripts in [a later lesson](https://carpentries-incubator.github.io/shell-metagenomics/05-writing-scripts/index.html)." links back to the same episode.

3) In the [Writing Scripts and Working with Data](https://carpentries-incubator.github.io/shell-metagenomics/05-writing-scripts/index.html) episode, the "Transferring data between your local machine and the cloud" needs to be adapted to also fit the case of a local installation - or be provided with a possible alternative.

4) In the [Writing Scripts and Working with Data](https://carpentries-incubator.github.io/shell-metagenomics/05-writing-scripts/index.html) episode, the section on "Versioning scripts with Git and GitHub" would lead to a confusion, given the target audience. Although knowledge of Git is undoubtedly a useful skill, it may not be easily connected here.

**Comment by Czirion** [comment]
1. Added text and screenshot
2. Removed line
3. Pending...
4. Removed Git part

**Comment by fabel134** [comment]
Creo que ya termine :)

**Comment by nselem** [comment]
Please, explain what did you do, for the reviewers

**Comment by fabel134** [comment]
This Issue was fixed by adding steps to be able to download and upload data from an R Studio online terminal. Also added a note that talks about alternatives to download and upload data.

**Comment by fabel134** [comment]
The sizes of the figures will be adjusted so that they can be readable

**Comment by nselem** [comment]
Great work. Now you need to have all images in English. The last ones have a legend "seleccionar archivo" en español and we need all images in English.
