### ISSUE TITLE
Break lessons that took a lot of time to teach

### ISSUE THREAD

**Issue by AbrahamAvelar** [carpentries-lab/metagenomics-analysis#5]
The "Diversity analysis" and the "Taxonomic Assignation" lessons lasted for over an 1.5 hours. I thinkj both of them  should be split into two lessons.

**Comment by nselem** [comment]
R lesson has been split into 4 episodes, where Spanish text need to be removed

**Comment by Czirion** [comment]
Check this with comments from reviewers.

**Comment by Czirion** [comment]
Allready covered in another issue
