### ISSUE TITLE
Improve Assessing Read Quality episode

### ISSUE THREAD

**Issue by Czirion** [carpentries-lab/metagenomics-analysis#57]
**Reviewer's comment**: In the [Assessing Read Quality](https://carpentries-incubator.github.io/metagenomics/02-assessing-read-quality/index.html) episode, the "Exercise 2: Looking at files metadata" could be better structured, in order for each answer to provide a different context to the original question.

**Comment by nselem** [comment]
In this exercise, we want to reinforce the metadata concept from the previous episode while exploring the file's quality. In the exercise, we added a description that metadata about files comprises owners, permissions, sizes, and modification dates. The answers have been updated. Also, we want to motivate learners to search in google or in bash manuals for different flags expecting to increase their confidence in searching for help.
