### ISSUE TITLE
Provide files created during the lesson

### ISSUE THREAD

**Issue by Czirion** [carpentries-lab/metagenomics-analysis#59]
**Reviewer's comment**:The file cuatroc.biom that is used for the work in episode [Diversity Tackled With R](https://carpentries-incubator.github.io/metagenomics/07-Diversity-tackled-with-R/index.html) would be useful to be provided (in case learners encountered issues creating it).

**To do**: Make sure that the file is in the hidden backup directory and put a note somewhere about it.

**Comment by nselem** [comment]
Also adapter file must be in the hidden directory 
https://drive.google.com/file/d/13ZXMk8TVVY2j4L1cfbYPe_X62L0jTQS7/view

**Comment by nselem** [comment]
The data in Zenodo has been updated. Now it has a hidden backup directory with all the original files and all the relevant results, including the cuatroc.biom, the TruSeq adapter file and more.
