### ISSUE TITLE
Change name of Data Files

### ISSUE THREAD

**Issue by AbrahamAvelar** [carpentries-lab/metagenomics-analysis#6]
Data files have very long unreadable names. Given the size of the shell window it quickly becomes very difficult to follow when multiple arguments and files are to be together in commands. I think it would be more didactic if filenames were shorter and more descriptive. I think a simple cp + mv would work at the begining when also teaching the importance of keeping raw data untouched.

**Comment by CladoniaRang** [comment]
I'll also do this part, Vanessa.
