### ISSUE TITLE
Exercises and discussions in Data processing lesson

### ISSUE THREAD

**Issue by Czirion** [carpentries-lab/metagenomics-analysis#60]
**Reviewer's comment**: Most exercises are command-line based, adding more conceptual questions or discussion could help evaluate understanding and relevance of the topic better.

**Comment by Bedxxe** [comment]
Added discussion boxes to asses the understanding and relevance of the tackled topics in episodes:
01-background-metadata
02-assessing-read-quality
04-Metagenome Assembly
05-binning
06-taxonomic
08-Diversity-tackled-with-R
