### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Czirion** [carpentries-lab/metagenomics-analysis#61]
**Reviewer's comment**: Throughout the lesson, there are several small typos that need fixing. :)

**To do**: Review all episodes for typos and correct them.

**Comment by nselem** [comment]
Typos and style have been reviewed with Grammarly software for the lessons: 
- [x] [Project Organization and Management](https://carpentries-incubator.github.io/organization-metagenomics/) episodes. 
To do:
- [] [Introduction to the Command Line](https://carpentries-incubator.github.io/shell-metagenomics/)
- [] [Introduction to R](https://carpentries-incubator.github.io/introduction-to-R-for-metagenomics/)
- [x] [Data Processing and Visualization for Metagenomics](https://carpentries-incubator.github.io/metagenomics/)

**Comment by Bedxxe** [comment]
I did the correction of the typos inside Introduction to R
