### ISSUE TITLE
Required software setup section

### ISSUE THREAD

**Issue by Czirion** [carpentries-lab/metagenomics-analysis#62]
**Reviewer's comments**:
1)The Windows installation instructions for Git are not up-to-date (there are additional steps in the installer - as of 27/06/2022). Additionally, for the Mac instructions, and in addition to the video that is helpful, the link to the software could be added directly as well (for convenience).

2) Option B: there are several links to the manual pages of the required software that are missing. This poses a challenge when trying to find the installation instructions (a clear case is the CheckM-genome software that requires a bit of an effort to find the install instructions). Additionally, the version of trimmomatic is listed as 0.38, but only versions 0.37/0.39/0.40 are available on the linked page. Finally, the link to the [MaxBin2](https://carpentries-incubator.github.io/metagenomics-workshop/setup.html) software links back to the workshop page.

3)  A local installation through conda was challenging, as the current versions led to multiple conflicts that could not be resolved. This was equally true both when installing each tool independently, and when using the provided yaml file. However, using the specification file (listed under Option A), it was possible to create a working environment. It may be useful to highlight the specification file also as an option to create a local instance (including the few commands that need to be executed as the final step), as well as for setting up the AWS instance.

4) The table "Software for Bash" might need some edits, e.g. removing or updating the "Available for" entries, and also moving the description of the KronaTools to the appropriate column.

**Comment by lugetego** [comment]
Commit changes on setup section.

Upload new specifications and yml files.

Create a yml files of metagenomics env with the necessary packages for each operating system:
metagenomics-Ubuntu22.yml  (contains the complete list of necessary packages: fastq, trimmomatic, metaspades, maxbin2, checkm, kraken2, krona) 

metagenomics-macOS.yml (contains the the next packages: fastq, trimmomatic, metaspades, maxbin2, checkm, kraken2, krona). With macOS Monterey Maxbin2 fails on FragGeneScan step. I think is problem of the C99 standard of the program FragGeneScan and the version of the g++ compiler installed on macOS. 

metagenomics-WSLUbuntu.yml (contains the the next packages: fastq, trimmomatic, metaspades, checkm, kraken2, krona). Maxbin2 and Checkm-genome are incompatible and is not possible to install them together.  I installed the maxbin2 package in a different environment.

Create a video tutorials following the lesson instructions to test the tools.
metagenomics WSL - https://youtube.com/playlist?list=PLNO3QBRSdaTLVJvWjxBY-PoNVI_PVQtp6
metagenomics Ubuntu - https://youtube.com/playlist?list=PLNO3QBRSdaTJqQcIk51VxMG0zoauSOXvs  
metagenomics macOS - https://youtube.com/playlist?list=PLNO3QBRSdaTKF0gn40ODedjnecRYFd03h

**Comment by Czirion** [comment]
Thanks for the ymls Luis. 
I have a doubt. Are we changing the setup for Windows to now use WSL instead of Git for Windows? Or are we going to put the setup instructions the two alternatives?

**Comment by lugetego** [comment]
I believe WSL is the best option. I don't know how you are using Git for Windows during the lesson. If only use Git for Windows and their Git bash, the installation of the conda packages with this option should be different. Maybe is necessary to remove Git for Windows as an alternative on the setup instructions. The same for the Putty program, if only need it to connect through SSH, you can use the PowerShell that is already installed on Windows 10 and 11.

https://learn.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7.2

**Comment by Czirion** [comment]
1) There is no "link to the software" because the Terminal app comes installed with the Mac Operating Systems.

2) Trimmomatic now mentions Version 0.39. Maxbin2 does not have a proper website, only the SourceForge for the download. The installation of the packages is intended to do with the conda environment. The installation of the exact versions individually is in the version column. And the installation for CheckM from their website is in the link of the Github wiki.

3) The instructions for making the environment in each OS have been added, and the Spec file has been highlighted as the recommended option. 

4) The table has been improved.
