### ISSUE TITLE
R no despliega graficas

### ISSUE THREAD

**Issue by Czirion** [carpentries-lab/metagenomics-analysis#63]
Hacer que en el pipeline se guarden las graficas y abrirlas desde un archivo para que se puedan ver.

**Comment by nselem** [comment]
all plots in lesson have been saved in a file

**Comment by Czirion** [comment]
Plots will change because of the changes that I am doing in the taxonomy episodes.

**Comment by nselem** [comment]
You will need to add these lines before and after the plot ..
> pdf("plot_abundances.pdf",width = 15, height = 5) 
> ggplot (your plot ...)
> dev.off()

**Comment by Czirion** [comment]
Add ggsave line to all R images in Intro to R and phyloseq episodes

**Comment by nselem** [comment]
Since in the instance the plotting is going to work, I just added a note at instructor notes.. that sometimes images are not displayed in local installation, and then you need to save the images using:  
pdf("plot_abundances.pdf",width = 15, height = 5)
ggplot (your plot ...)
dev.off()
