### ISSUE TITLE
Integrate Shell lesson within the metagenomics lesson

### ISSUE THREAD

**Issue by AbrahamAvelar** [carpentries-lab/metagenomics-analysis#7]
Although jumping between the Metagenomics and the "Introduction to the Command line for Genomics" was good enough, there are a bunch of bash commands required to parse metagenomics files, mostly in the Diversity analysis lesson. I think teaching Shell could be better integrated, ideally, the relevant lessons from "Introduction to the command line for genomics" should be carried out using data to be used in the metagenomics pipeline.

**Comment by CladoniaRang** [comment]
I will do this part, Vanessa.

**Comment by aaronejaime** [comment]
Going to help you out with this

**Comment by Czirion** [comment]
Check if that integration is already achieved.
