### ISSUE TITLE
The AMI is dirty

### ISSUE THREAD

**Issue by Czirion** [carpentries-lab/metagenomics-analysis#78]
When you open the RStudio server from the AMI it has open script, content in the consol and environment , and a plot
We need to crean the image in AWS

**Comment by tobyhodges** [comment]
Is this something you need help from the Core Team to do, or are you able to access and edit the AMI on your own?

**Comment by nselem** [comment]
Hello Toby, 
We need help from the Core Team. We need an AWS instance that we can clean and update with the last environment changes, to keep IP up to date with the setup section. And then, the Core team needs to make this new instance the "official" one . Could you help us by providing us with an instance?

**Comment by tobyhodges** [comment]
I'll set up an instance and follow up with you by email to share the connection details.

**Comment by Czirion** [comment]
The instance has been updated and all the software tested, it is ready to become an image
