### ISSUE TITLE
Add R to the remote computer

### ISSUE THREAD

**Issue by AbrahamAvelar** [carpentries-lab/metagenomics-analysis#8]
The Diversity analysis required to jump from command line in the remote computer to Rstudio in each student's local computer. This brought incompatibilities in versions and OSs. It would be better to done as much as possible in the same interface and just bring files to local computer when it is most likely to work for everyone (in eg. just the JPG figures from R)

**Comment by nselem** [comment]
I just noticed R was already there using port 8787
Ej http://ec2-3-235-238-92.compute-1.amazonaws.com:8787 
opens an R studion in the browser
