### ISSUE TITLE
Update README and _config.yml to use DOI from JOSE

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-lab/metagenomics-analysis#85]
Since [the paper was accepted](https://github.com/openjournals/jose-reviews/issues/209#issuecomment-1944741978) (congratulations!), the `doi` field of `_config.yml` can now be updated to use the DOI from JOSE. The badge and citation info in the README can also be updated.

**Comment by nselem** [comment]
Badge on readme has been updated with ![DOI](https://jose.theoj.org/papers/10.21105/jose.00209/status.svg) and doi "https://doi.org/10.21105/jose.00209"  has been added to `_config.yml`
